# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Zalo Mini App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: write
  repository-projects: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npx zmp-developer-token login ${{ secrets.ZALO_APP_ID }} ${{ secrets.ZALO_APP_SECRET }} ${{ secrets.ZALO_REFRESH_TOKEN }} >> $GITHUB_ENV
    - uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'ZALO_REFRESH_TOKEN'
        value: ${{ env.NEW_REFRESH_TOKEN }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - name: Use the value
      id: step_two
      run: |
        echo $ZMP_TOKEN
    - run: npm install -g zmp-cli
    - run: npm run deploy:auto
